<!DOCTYPE html>
<html>

<head>
  <title>Registro</title>
  <link rel="stylesheet" href="/css/main.css">
</head>

<body>
  <div class="form register-form">
    <h1>Registro</h1>
    <form action="/registro" method="post">
      <label for="fname">First name:</label>
      <input type="text" name="fname" class="text name"><br><br>
      <label for="lname">Last name:</label>
      <input type="text" name="lname" class="text lname"><br><br>

      <label for="cars">Choose a car:</label>

      <select name="cars" id="cars">
        <option value="volvo">Volvo</option>
        <option value="saab">Saab</option>
        <option value="mercedes">Mercedes</option>
        <option value="audi">Audi</option>
      </select><br><br>

      <label for="motos">Choose a Moto:</label>
      <select name="motos" id="motos">
        <option value="volvo">Volvo</option>
        <option value="saab">Saab</option>
        <option value="mercedes">Mercedes</option>
        <option value="audi">Audi</option>
      </select>
      <br><br>
      <input type="submit" value="Submit">
    </form>
  </div>
</body>

</html>
